language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: assemblymade/gallipoli
  api_key:
    secure : "YF1V1vEUiKVsb8jFfCoVrX0NcQfRRq7JDWX+MRymBR9+TTieNLRDeNCiEmQrODo3fptgIp7HdJbS7pdLnBGqMN6Mwi7p4BjQYL9EiC/EbiTnS7+BAbClF/oqEeEjZ8AkGiXAJCdyEg49Gc0Ac28mIeivm3GMZK9Ki5vRP/F1hls="

  strategy: git
 before_deploy:
- git fetch --unshallow
