language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: gallipoli-assembled
  api_key:
    secure : "ZQKjlXO459PXGj+EZVumRLmDZaRCyY3MQ2QUg/cXBVYONjglZzmHy2hgDXh+Clt3el/gbCyn5uY/5Xak/Y0WsUOMX/RaWIp8/qH4lCWIoEXj2KyschpMmaWV7gPiiltKGZQp2ha0nDLTYpePg4H2/1VexuSfKRESNl96XJzg2nU="
  strategy: git
 before_deploy:
- git fetch --unshallow
