language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: moonbase-assembled
  api_key:
    secure : "LhBPLVw0Ccej+HGHAtZkmJ8MdYIz+AVB0oS9pinnRHE+6rhp92xtoi7uaeVJKfw2bfbCgw0dh0kilLysLqXWN8NFbeW+nLongeOo6sn4qFSAY1ZNnprsbJD6UQHcHoon9W6LJgJvtRbw//in5kYQdf2nvZTyl8GQtZ9Q8bZivcI="
  strategy: git
